[32mINFO    [0m test_ui_login:test_ui_login.py:33 初始化测试环境
[32mINFO    [0m common.model.function:function.py:44 开始读取YAML文件: E:\Demo\软件测试\比赛准备\AutoTest\Demo_second\common\config\ui_config.yaml
[32mINFO    [0m common.model.function:function.py:50 成功读取YAML文件: E:\Demo\软件测试\比赛准备\AutoTest\Demo_second\common\config\ui_config.yaml
[32mINFO    [0m ui_test.page.base_page:base_page.py:17 打开网址: http://192.168.46.5:41805/login?redirect=%2Findex
[32mINFO    [0m test_ui_login:test_ui_login.py:87 开始测试无效登录
[32mINFO    [0m test_ui_login:test_ui_login.py:88 测试用例参数 - 用户名: XTGLY, 密码: wrong_password
[32mINFO    [0m ui_test.page.base_page:login_page.py:33 输入用户名:XTGLY
[32mINFO    [0m ui_test.page.base_page:login_page.py:40 输入密码:wrong_password
[32mINFO    [0m ui_test.page.base_page:base_page.py:21 点击元素: ('id', 'signIn')
[32mINFO    [0m test_ui_login:test_ui_login.py:98 验证错误信息: 登录密码错误
[32mINFO    [0m test_ui_login:test_ui_login.py:38 清理测试环境
[32mINFO    [0m ui_test.page.base_page:base_page.py:31 关闭浏览器